### ISSUE TITLE
Request to add more awesome content

### ISSUE THREAD

**Issue by Jassi10000-zz** [ericelliott/react-things#18]
Heyy @ericelliott  , the content is awesome , 
Can you pls add some content related to  React- three- fiber , react - gatsby  etc.
I would love to learn more here

**Comment by ericelliott** [comment]
This is very old and no longer maintained.

I don't use gatsby or react three fiber so I'm not the person to do that. Maybe you should?

In the meantime, my current stack looks like this:

* [Next.js](https://nextjs.org/) on [Vercel](https://vercel.com/)
* React + Redux + [Autodux](https://github.com/ericelliott/autodux) + [Redux-dsm](https://github.com/ericelliott/redux-dsm)
* [Firebase](https://firebase.google.com/) or [FaunaDB](https://fauna.com/)
* [Magic](https://magic.link/) for auth & blockchain wallets
